### ISSUE TITLE
Issue on M3 Macbook

### ISSUE THREAD

**Issue by fredlef** [11cafe/comfyui-workspace-manager#103]
Works as expected on Windows machine with ComfyUI portable.  That is when clicking on a workflow from the list the workflow opens in the UI.  When clicking on a workflow from the list on Macbook Pro it displays a white box with Save or Discard options (see attachment).
<img width="1124" alt="Workflow Mac Issue" src="https://github.com/11cafe/comfyui-workspace-manager/assets/40640070/15847ca9-a815-457b-a0d6-9bb309ed826f">

Thanks

**Comment by Weixuanf** [comment]
hi sorry i noticed this too. can you switch to dark mode for now before my fix, the dark mode works

**Comment by Weixuanf** [comment]
![Uploading Screenshot 2024-01-11 at 6.13.05 PM.png…]()

**Comment by Weixuanf** [comment]
<img width="240" alt="Screenshot 2024-01-11 at 6 13 05 PM" src="https://github.com/11cafe/comfyui-workspace-manager/assets/18367033/278655eb-8b00-4749-9b29-dcb56f23f629">

**Comment by fredlef** [comment]
Hi - so when I do dark mode i get text in the box but the workflow doesn't open.  When I click on the workflow in Windows it just opens the workflow for use - which I think would be the preferred option.  On Mac there is the prompt.  If the prompt is the preferred option then perhaps there should be three choices - open/save/discard.

Thanks

**Comment by Weixuanf** [comment]
oh i see what's happening, in mac you have the new version, we are disabling auto save on default, in that case, you will have to choose save/discard before switching workflow otherwise your changes will be lost.

but now I found disabling auto saving on default is not a good user experience, so i fixed it back in new version: https://github.com/11cafe/comfyui-workspace-manager/pull/104

update to latest on you mac and make sure "Enable auto saving" is checked in settings and you will have the old behavior like your windows. 

<img width="565" alt="Screenshot 2024-01-11 at 7 35 09 PM" src="https://github.com/11cafe/comfyui-workspace-manager/assets/18367033/2bd6bb13-b1cf-4d0d-8a56-cf9588fa220e">

**Comment by fredlef** [comment]
Oh this sounds great - thanks!
