### ISSUE TITLE
Where did you hide the workflow data information?

### ISSUE THREAD

**Issue by jinnaluo0** [11cafe/comfyui-workspace-manager#108]
There are 30 workflows in my comfyUI, and now I have downloaded a brand new comfyUI and started it, and this new comfyUI automatically obtains 30 workflows.
So,where did you hide the workflow data information?

**Comment by Weixuanf** [comment]
Oh it’s in your browser cache. F12 or Inspect and you go to applications tab and indexdb to see it

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: jinnaluo0 ***@***.***>
Sent: Saturday, January 13, 2024 12:15:46 PM
To: 11cafe/comfyui-workspace-manager ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [11cafe/comfyui-workspace-manager] Where did you hide the workflow data information? (Issue #108)


There are 30 workflows in my comfyUI, and now I have downloaded a brand new comfyUI and started it, and this new comfyUI automatically obtains 30 workflows.
So,where did you hide the workflow data information?

**Comment by Weixuanf** [comment]
We probably want to migrate to use indexdb (browser cache) only so that we make far less network requests and disk file read/write and you can retain your data even you reinstall comfyui. I wonder how do you feel about us storing it to your browser cache? Do u think it’s acceptable

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jinnaluo0** [comment]
thanks
