### ISSUE TITLE
A very serious problem

### ISSUE THREAD

**Issue by cheezmil** [11cafe/comfyui-workspace-manager#14]
When I copy some nodes with Ctrl+C and then Ctrl+V them out, I can't copy and paste other different nodes anymore!!! The pasted nodes have always been the first copied nodes

When I install this plugin, this problem occurs

When I delete this plugin, this problem won't occur

当我ctrl+c复制一些节点的时候,然后将它们ctrl+v出来,就不能再复制粘贴另外不同的节点了!粘贴出来的一直都是第一次复制的节点
当我安装了这个插件就会出现这样的问题
当我删除了这个插件就不会出现这样的问题

**Comment by Weixuanf** [comment]
hi thank you for filing this bug,
I just published the fix for this issue, you can update to the new version and see if the problem goes away. Please do let me know!
Also if you have discord, you can add me: briefpeach 
I would love to learn some user feedbacks in depth!
or any other communication if you prefer, wechat, telegram, ...
