### ISSUE TITLE
Your plugin destroyed all my workflows

### ISSUE THREAD

**Issue by unoriginalscreenname** [11cafe/comfyui-workspace-manager#193]
The actual management of the workflows is a mess in the flyout window.  But the worst is I just tried to change the save directory it adds a '/' in front of the local location and begins throwing an error in the console.  

OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '/C:'

When  I looked for all of my original workflows, it turns out that it had completely erased them all.  I can't tell you how many hours of my time is now just gone.

**Comment by Weixuanf** [comment]
Hi, sorry for the issue you encountered.
1. please do not use two way sync since it's not stable yet and can have bugs. Really sorry about this, we should have made it more clear that it's not ready to use.
2. All your workflows are primarily stored in your browser cache (IndexDB), and backedup in your disk (In your case, it seems you lost your disk backup files, but your browser cache should still be there). So you should be able to recover it. Could you please screenshot your browser IndexedDB and I'll show you how you can recover it. You can F12 or browser right click menu -> Insepect -> Application (called "Storage" in Firefox) -> IndexedDB
<img width="414" alt="Screenshot 2024-02-11 at 8 39 21 AM" src="https://github.com/11cafe/comfyui-workspace-manager/assets/18367033/7d98c154-bef2-4aca-b7b0-7204c3c277d5">

**Comment by Weixuanf** [comment]
navigate to IndexedDB -> comfyui_workspace_db -> workflows to see your workflow data:

<img width="550" alt="Screenshot 2024-02-11 at 9 03 53 AM" src="https://github.com/11cafe/comfyui-workspace-manager/assets/18367033/35122010-95e3-45b2-8ecb-e35241151b86">

if you do not see IndexedDB -> comfyui_workspace_db but see IndexedDB -> WorkspaceDB instead, you can still recover it by deleting your local comfyui-workspace-manager/db/ folder
