### ISSUE TITLE
Workspace manager conflict

### ISSUE THREAD

**Issue by kakachiex2** [11cafe/comfyui-workspace-manager#268]
I have various ComfyUI installed one for stable extension and one for experimental extension that use old library's and are unstable.
When I load the experimental version and load all workflow and later load the stable ComfyUI the workspace M. load the workflow in the experimental version of ComfyUI not the one in the stable version and it even point to the experimental folder location.

**Comment by kakachiex2** [comment]
I change the folder location to the stable version and keep loading the workflow in the experimental version.
![Screenshot 2024-03-11 215452](https://github.com/11cafe/comfyui-workspace-manager/assets/1762112/760a0880-deea-4ba9-9436-636ce6845a8d)

**Comment by Weixuanf** [comment]
Hi it seems you’re in old version.

can you update to latest version? https://github.com/11cafe/comfyui-workspace-manager/tree/main?tab=readme-ov-file#v20-beta-two-way-sync-with-local-folder-select-model-install-path-cloud-sync-workflows

In latest version we can load workflows directly from your selected folder. But you need to manually switch to different my_workflows/ folders when you switch ComfyUI/, otherwise even if you changed comfyui, it will still remember the last my_workflows/ location you used

**Comment by kakachiex2** [comment]
Ok thanks @Weixuanf
