### ISSUE TITLE
Model preview no longer respects folders

### ISSUE THREAD

**Issue by HaydenReeve** [11cafe/comfyui-workspace-manager#293]
This, I understand, may be intended as a feature. However, there is a use-case issue here in that should you be often involved with switching between architectures you may want to separate your architectures by folders, logically.

![image](https://github.com/11cafe/comfyui-workspace-manager/assets/39004735/e256dd37-0467-4019-a2c1-9caff24f9d81)

As you may be able to see, by filtering to Loras, I am provided with only the names of the models. This is absolutely preferable att a glance, but in a use-case where each lora here is deliminated by a folder such as "SD" or "SDXL" for example, suddenly I am unable to tell at a glance which are available within the current workflow's architecture.

Providing the ability to filter via subfolders would be the optimal outcome here, although, providing the full path name is also a way to resolve the issue like it used to.

**Comment by Ratinod** [comment]
Everything related to "Models" has a lot of problems.
- Will there be an option to disable hash calculation? Will there be an option to COMPLETELY disable access to external servers to obtain any information (in this case, previews and now names)? As the person above wrote, I prefer to see the name lora or a path with a name.
- I would also like the option that when you click on a file icon, it will not open the civitai website, but rather open the folder with the file in the default system explorer.
- Why does the category reset every time? (For example, I chose “lora”, closed it, opened it and “checkpoints” is loaded again)
- search query is not saved
- Why does the search ignore the previously selected category? If I select lora then I expect that the search will be performed only in lora.
- Because of the point above, all the top search results are filled with completely incorrect results. (controlnet's, ip-adapter's...)
- When I enter the exact name of something, I expect to see a complete elimination of results that do not match the query. For example, if I enter "style" I expect to see results where there is "style" in the name of the file or folder/subfolder. However, as a result, I get a bunch of results that are not related to this word at all (for example: taesd_decoder.pth, OTHER\emb_claystat.pt, control_v11f1e_sd15_tile.pth, 8x_NMKD-Superscale_150000_G.pth...)
- if I enter something like "\style\" it implies that I only want to see files in matching folder structures in the results.

Naturally, it’s clear to me that you won’t encounter these problems if you have a couple of dozen lora's and they all just lie in one folder without a sub-folder structure.

**Comment by Weixuanf** [comment]
hi we do get request to add folder support in models list, but just haven't got bandwidth to do it 🫠 so many to-do things

>Will there be an option to disable hash calculation? Will there be an option to COMPLETELY disable access to external servers to obtain any information

i see, we can add a settings in menu to disable it

>I expect to see a complete elimination of results that do not match the query. For example,

right this is prob the expected behavior. we added some fuzzy search, but its prob not desired 😿
@arslan2012  can we make fuse search more strict following query and less fuzzy

>I would also like the option that when you click on a file icon, it will not open the civitai website, but rather open the folder with the file in the default system explorer.

this would be something nice to have

thanks for all these suggestions..we're just a bit short on bandwidth. Eventually I hope we can finish them all 😊

**Comment by HaydenReeve** [comment]
Hey @Weixuanf,

The original intention of this ticket would be solved by using the filename instead of the CivitAI published name like it used to. Hopefully, that might make the decision easier for you.

The issue is that using the CivitAI name hides the file name, including the folder directory, which impacts sorting and means that you no longer have an organised list. If you use the file name, with a full path like it used to, you keep your sort-by-folder structure as things appended with a folder will be grouped.

e.g.:
```
SD/Something
SD/Zoomer
SDXL/Something1
SDXL/Foobar
SDXL/GreatBreakfast
```

I appreciate the incredible work that has been put into this repo. Hopefully, these suggestions are helpful to you. :)

Cheers

**Comment by arslan2012** [comment]
@Ratinod 
> * I would also like the option that when you click on a file icon, it will not open the civitai website, but rather open the folder with the file in the default system explorer.

It is impossible to open local file/dir from a web browser.
Have you even seen any website/SD UI that can do this?
![image](https://github.com/11cafe/comfyui-workspace-manager/assets/8698442/014a0f36-2f71-4a07-ae1a-b24a78ffee9e)

> * Why does the category reset every time? (For example, I chose “lora”, closed it, opened it and “checkpoints” is loaded again)

fixed in next version
> * search query is not saved

fixed in next version
> * Why does the search ignore the previously selected category? If I select lora then I expect that the search will be performed only in lora.

fixed in next version
> * When I enter the exact name of something, I expect to see a complete elimination of results that do not match the query. For example, if I enter "style" I expect to see results where there is "style" in the name of the file or folder/subfolder. However, as a result, I get a bunch of results that are not related to this word at all

added a setting for this in next version
> * if I enter something like "\style\\" it implies that I only want to see files in matching folder structures in the results.

this is supported, I think the search needs to be like "style\\", without the slash in front.

**Comment by Weixuanf** [comment]
> Hey @Weixuanf,
> 
> The original intention of this ticket would be solved by using the filename instead of the CivitAI published name like it used to. Hopefully, that might make the decision easier for you.
> 
> The issue is that using the CivitAI name hides the file name, including the folder directory, which impacts sorting and means that you no longer have an organised list. If you use the file name, with a full path like it used to, you keep your sort-by-folder structure as things appended with a folder will be grouped.
> 
> e.g.:
> 
> ```
> SD/Something
> SD/Zoomer
> SDXL/Something1
> SDXL/Foobar
> SDXL/GreatBreakfast
> ```
> 
> I appreciate the incredible work that has been put into this repo. Hopefully, these suggestions are helpful to you. :)
> 
> Cheers

@HaydenReeve thanks very much for your explanation! I've just pushed the update to show up the folders:

<img width="451" alt="Screenshot 2024-03-27 at 11 45 51 PM" src="https://github.com/11cafe/comfyui-workspace-manager/assets/18367033/5d017ac3-fda5-482d-a64f-b1579c682051">

please update and see if it works for you. Sorry for the delayed response. Have been really busy and tired recently.

**Comment by HaydenReeve** [comment]
Yes, it works brilliantly. Thank you very much! :)
