### ISSUE TITLE
TypeError: stat: path should be string, bytes, os.PathLike or integer, not dict

### ISSUE THREAD

**Issue by hcms1994** [11cafe/comfyui-workspace-manager#296]
Hi,
   After I installed this plugin, when I opened Comfui and selected the import workflow, this error was displayed. Why

![image](https://github.com/11cafe/comfyui-workspace-manager/assets/33867247/abc3987a-9fe5-41dd-80b9-e3ed00ee08e0)

**Comment by goulchen** [comment]
It's because the curDir var is expected to be a string but is in fact a dict. 

In db_service.py around line 58 I replaced 
`curDir = records[DEFAULT_USER]['myWorkflowsDir']`
by 
`curDir = records[DEFAULT_USER]['myWorkflowsDir']['path']`

and it worked for me

**Comment by Weixuanf** [comment]
https://github.com/11cafe/comfyui-workspace-manager/commit/68bc2750451bd1c194916aa13026df04fedcd6f7

should be fixed in latest, please try and see if it works, thank you!!

**Comment by Weixuanf** [comment]
> It's because the curDir var is expected to be a string but is in fact a dict.
> 
> In db_service.py around line 58 I replaced `curDir = records[DEFAULT_USER]['myWorkflowsDir']` by `curDir = records[DEFAULT_USER]['myWorkflowsDir']['path']`
> 
> and it worked for me

thanks for finding a solution, but this may not be compatible with later updates as `records[DEFAULT_USER]['myWorkflowsDir']` should store a string, not a dict. It was due to a bug that it stored a dict. Therefore, please still update to latest to resolve the bug completely. Thank you very much for helping out!

**Comment by Weixuanf** [comment]
also please go to Settings > My workflows save directory to **Reset** and **Save** your workflows directory again so you don't experience problems in future. Due to the temporary bug your user settings json value is probably malformed, better overwrite it again, thank you!!

<img width="323" alt="Screenshot 2024-03-19 at 8 12 56 PM" src="https://github.com/11cafe/comfyui-workspace-manager/assets/18367033/915844c4-bdd7-4f0b-a0c6-8eaeeb2d6066">
