### ISSUE TITLE
Autosave duration only changes after restarting ComfyUI

### ISSUE THREAD

**Issue by LukeG89** [11cafe/comfyui-workspace-manager#327]
Hi @Weixuanf, not a big issue but I've noticed that the autosave duration doesn't change right away. You have to restart ComfyUI in order to make it save with the new duration. Is it expected?

**Comment by Weixuanf** [comment]
I think you just need to refresh page after changing a setting. No need to  restart comfyui server
________________________________
From: LukeG89 ***@***.***>
Sent: Friday, March 29, 2024 3:02:27 AM
To: 11cafe/comfyui-workspace-manager ***@***.***>
Cc: Weixuan Fu ***@***.***>; Mention ***@***.***>
Subject: [11cafe/comfyui-workspace-manager] Autosave duration only changes after restarting ComfyUI (Issue #327)


Hi @Weixuanf<https://github.com/Weixuanf>, not a big issue but I've noticed that the autosave duration doesn't change right away. You have to restart ComfyUI in order to make it save with the new duration. Is it expected?

**Comment by LukeG89** [comment]
Ah ok! Thanks! 😄
