### ISSUE TITLE
Save function

### ISSUE THREAD

**Issue by WeirdScienceX** [11cafe/comfyui-workspace-manager#369]
Since the recent update I am no longer able to save the workflow.

![firefox_H7SdEaPcxU](https://github.com/11cafe/comfyui-workspace-manager/assets/1296569/6a5985fa-cbf2-4ab3-94f9-715e7a7c6c0c)

**Comment by Weixuanf** [comment]
After you click it, it should ask you to input a name, then you should be able to save. Is it not saving for you after you enter the name?
________________________________
From: WeirdScienceX ***@***.***>
Sent: Monday, May 13, 2024 2:52:40 AM
To: 11cafe/comfyui-workspace-manager ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [11cafe/comfyui-workspace-manager] Save function (Issue #369)


Since the recent update I am no longer able to save the workflow.

firefox_H7SdEaPcxU.png (view on web)<https://github.com/11cafe/comfyui-workspace-manager/assets/1296569/6a5985fa-cbf2-4ab3-94f9-715e7a7c6c0c>

**Comment by Weixuanf** [comment]
I should fix the label of the button, from “new workflow” to “save workflow” in the screenshot
________________________________

**Comment by WeirdScienceX** [comment]
When I click the button nothing happens
![firefox_cLO94dJUhK](https://github.com/11cafe/comfyui-workspace-manager/assets/1296569/752bde00-3ae6-4f9e-93ec-1828327fd6e7)

**Comment by WeirdScienceX** [comment]
This is what I see with all other custom nodes disabled apart from comfyui manager
![ShareX_KiujyPnSxL](https://github.com/11cafe/comfyui-workspace-manager/assets/1296569/74363b8d-a19f-4a2c-af6a-fa4cb1a12252)

**Comment by Weixuanf** [comment]
can you update again to see if this issue is fixed? I just pushed a fix

**Comment by WeirdScienceX** [comment]
Yes, that seems to have resolved the issue, thanks for the quick fix :)
