### ISSUE TITLE
Hardcoded nodecafe url

### ISSUE THREAD

**Issue by CPapadim** [11cafe/comfyui-workspace-manager#395]
I noticed that nodecafe.org is hardcoded in a couple of files but no functionality around it is mentioned in the README

Specifically, here:  

[service/media_service.py](https://github.com/11cafe/comfyui-workspace-manager/blob/74be8c1e082ca389495f1ff466d8311fb7147ff1/service/media_service.py#L12)

[ui/src/db-tables/UserSettingsTable.ts](https://github.com/11cafe/comfyui-workspace-manager/blob/74be8c1e082ca389495f1ff466d8311fb7147ff1/ui/src/db-tables/UserSettingsTable.ts#L46)

What is this url used for?  Are workflows or generated images uploaded there?

**Comment by Weixuanf** [comment]
Hi only when you click "Share" in File dropdown menu and it will be shared to nodecafe.org 

<img width="250" alt="Screenshot 2024-05-31 at 2 41 14 PM" src="https://github.com/11cafe/comfyui-workspace-manager/assets/18367033/a09a8d6b-38b1-40b7-ae04-3dd2feb5feb4">


<img width="542" alt="Screenshot 2024-05-31 at 2 41 09 PM" src="https://github.com/11cafe/comfyui-workspace-manager/assets/18367033/514abd9f-ef86-4a83-bee3-b657eb3f2619">


we're still in development so it's not mentioned anywhere. I hope to launch it soon. It will support backup your workflows to cloud (e.g. auto backup every 1 hour), and run your workflow in cloud GPU.

But only when you click "Share" it will upload to nodecafe.org , otherwise, it won't upload any data anywhere.
