### ISSUE TITLE
Model card thumbnail generation taking an inordinately long time

### ISSUE THREAD

**Issue by Ainaemaet** [11cafe/comfyui-workspace-manager#427]
Hello, I just discovered your wonderful project here today and very excited to use it. Unfortunately, when the program generates thumbnails for my models - it is taking a **very** long time. 

I've tried a number of times with the same result. It's been running for about a half hour now, and has maybe 16 of 180 or so models done. 

I'm running Comfy in WSL2 and the model folder is stored in the Windows filesystem - and while that can slow things down a little bit, I have things optimized in a way so everything else loads them quickly - and regardless, the speed at which it is going suggests something isn't working right.

**Comment by Weixuanf** [comment]
Hello! This is because it needs to calculate sha256 for each model file to be able to fetch the model info from civit ai otherwise it’s really hard to determine which model it is from the file name.

So it will be slow to fetch cover unfortunately. I plan to make this an optional process (only fetch when you click a button)
________________________________
From: Ainaemaet ***@***.***>
Sent: Saturday, June 29, 2024 11:37:15 AM
To: 11cafe/comfyui-workspace-manager ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [11cafe/comfyui-workspace-manager] Model card thumbnail generation taking an inordinately long time (Issue #427)


Hello, I just discovered your wonderful project here today and very excited to use it. Unfortunately, when the program generates thumbnails for my models - it is taking a very long time.

I've tried a number of times with the same result. It's been running for about a half hour now, and has maybe 16 of 180 or so models done.

I'm running Comfy in WSL2 and the model folder is stored in the Windows filesystem - and while that can slow things down a little bit, I have things optimized in a way so everything else loads them quickly - and regardless, the speed at which it is going suggests something isn't working right.

**Comment by Ainaemaet** [comment]
@Weixuanf thanks for the response. However, Auto1111 plugins like Civitai Browser + manage to do this in a fraction of the time; perhaps you could look there to see how they are doing it and use a similar technique in Comfy? 

Running CivBrowser+ I can get model info on all my models in about 15 minutes, whereas it takes this ComfyUI Workspace plugin close to that to get 2!

If that isn't a possibility, is there some way we can potentially use the info already download from that plugin to populate this one? 

I'm aware I'm talking about taking something built for a different program and implementing it here, but I've seen other node authors utilize such methods. 

At the rate this one works, I will have to leave it running for 3 days overnight to get all my models covered.

**Comment by Ainaemaet** [comment]
I already have images downloaded for the models, is it possible for me to copy them somewhere and have this plugin pick them up? 

I've tried finding where the model card thumbnails are being stored, but can't seem to find them.

**Comment by Ainaemaet** [comment]
Ok, well I've left it running and it's managed to get about half in 4 hours, so not as horrible as I originally thought (but still painfully slow). 

At least I only have to go through the process once, and then whenever I download new models. 

The plugin is still super cool.
